name: Rejestrator_Wilgotnosci
services:
  mqtt-broker:
    image: eclipse-mosquitto
    build:
      context: .
    ports:
      - 1883:1883 #  mqtt port
      - 9001:9001 #  websocket port
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log